const EN_MAP = {
  '1. 「你害怕失敗嗎？這個問題，我在暑假的最後一天終於找到了答案。」': '1. "Are you afraid of failure? I finally found the answer to this question on the last day of summer vacation."',
  '1. 「時間像流水一樣，一去不回頭。」': '1. "Time is like running water, once it passes, there is no turning back."',
  '1. 六要素是否完整？（時、地、人、因、經、果）': '1. Are the six elements complete?(time, place, person, cause, passage, effect)',
  '1. 呼應開頭式 — 回到起點，形成閉環': '1. Echo the opening formula - return to the starting point and form a closed loop',
  '1. 懸念式（用問題吊人胃口）| 2. 開門見山式（直接交代事件）| 3. 對話式（以對話開頭）| 4. 場景式（描寫環境氣氛）| 5. 開門見山式（直接交代事件 + 預告體悟）': '1. Suspense style (use questions to whet your appetite) | 2. Straight to the point (directly explain the incident) | 3. Conversational style (begin with a dialogue) | 4. Scenario style (describe the environment and atmosphere) | 5. Straight to the point (directly explain the incident + preview the realization)',
  '1. 明喻（有「像」）| 2. 暗喻（直接說「是」）| 3. 擬人（太陽「打呵欠」、「爬上來」）| 4. 誇張（呼嚕聲不可能傳到隔壁）': '1. Simile (with "like") | 2. Metaphor (directly saying "is") | 3. Personification (the sun "yawns" and "climbs up") | 4. Exaggeration (the snoring cannot reach the next door)',
  '1. 有問題（草草收場，像流水帳的結尾）| 2. 好結尾（感悟昇華式，從分數轉移到對自我的肯定）| 3. 有問題（感謝名單式結尾，空洞無真情實感）| 4. 好結尾（留白想像式，用具體畫面收尾，有韻味）': '1. Problematic (ending hastily, like the ending of a running account) | 2. Good ending (elevating feelings, moving from scores to self-affirmation) | 3. Problematic (ending like a thank you list, empty without true feelings) | 4. Good ending (leaving blank imaginative style, ending with a specific picture, with charm)',
  '1. 開門見山式 — 直接入題，不繞圈子': '1. Straight to the point - get straight to the point without going around in circles',
  '1. 順敘（按時間先後）— 最穩妥，考試安全牌': '1. Sequential description (in chronological order) - the safest and safest card for exams',
  '1.「就這樣，小學六年級的畢業典禮結束了。我們都要去不同的中學了。再見了，我的母校。」': '1. "That\'s it, the graduation ceremony of the sixth grade of elementary school is over. We are all going to different middle schools. Goodbye, my alma mater."',
  '2. 「去年暑假，我和家人一起去台北旅行。那是我第一次坐飛機。」': '2. "Last summer vacation, I traveled to Taipei with my family. It was my first time flying."',
  '2. 「書本是打開智慧之門的鑰匙。」': '2. "Books are the key to the door of wisdom."',
  '2. 倒敘（先說結局）— 製造懸念，吸引讀者': '2. Flashback (let’s talk about the ending first) – create suspense and attract readers',
  '2. 感悟昇華式 — 從事件提煉出人生道理': '2. Enlightenment sublimation type - extracting life principles from events',
  '2. 懸念式 — 拋出問題或懸疑，吊人胃口': '2. Suspense - raising questions or suspense to whet your appetite',
  '2. 開頭是否吸引人？（用了哪種開頭策略？）': '2. Is the beginning engaging?(Which opening strategy was used?)',
  '2.「我握著那張成績單，上面的分數比我預期的低了很多。但奇怪的是，我竟然沒有想像中難過——因為我知道，我已經盡了全力。」': '2. "I was holding the report card, and the scores on it were much lower than I expected. But the strange thing is that I wasn\'t as sad as I thought - because I knew that I had tried my best."',
  '3. 「『快起床！要遲到了！』爸爸的聲音像警鐘一樣劃破了早晨的寧靜。」': '3. "\'Get up! You\'re going to be late!\' Dad\'s voice cut through the morning tranquility like an alarm bell."',
  '3. 「太陽打了個呵欠，懶洋洋地從山後爬上來。」': '3. "The sun yawned and lazily climbed up from behind the mountain."',
  '3. 場景式 — 描寫環境，營造氣氛': '3. Scenery - describe the environment and create an atmosphere',
  '3. 插敘（中途補充）— 豐富層次，提供背景': '3. Narrative (added midway) - enrich the layers and provide background',
  '3. 是否有具體描寫？（五感／動作分解／心理層次）': '3. Is there a specific description?(Five senses/movement breakdown/psychological level)',
  '3. 留白想像式 — 不說盡，讓讀者自己回味': '3. Leave blank space for imagination – don’t tell everything, let readers reflect on their own',
  '3.「今天的事情讓我學到了很多。我要感謝老師的教導、同學的幫助、父母的照顧⋯⋯」': '3. "I learned a lot from today\'s events. I would like to thank my teachers for their teaching, my classmates for their help, and my parents for their care..."',
  '4. 「他的呼嚕聲大得連隔壁鄰居都跑來投訴。」': '4. "His snoring was so loud that even the next door neighbor came to complain."',
  '4. 「雨後的街道散發著泥土的清香，霓虹燈的光映在積水中，像一幅流動的油畫。」': '4. "After the rain, the streets exude the fragrance of earth, and the light of neon lights reflects in the standing water, like a flowing oil painting."',
  '4. 對話式 — 用人物的話開場，有臨場感': '4. Conversational style - start with the words of the characters, giving a sense of presence',
  '4. 意外反轉式 — 結尾來一個驚喜轉折': '4. Unexpected twist - a surprising twist at the end',
  '4. 結尾是否有力度？（用了哪種結尾策略？）': '4. Is the ending powerful?(Which ending strategy was used?)',
  '4.「我把那封信放進抽屜的最深處，沒有寄出去。窗外，鳳凰木的花正開得通紅。」': '4. "I put the letter in the deepest part of the drawer and did not send it. Outside the window, the poinciana flowers were blooming red."',
  '5. 「上星期六，我做了一件很傻的事，但這件事卻讓我學到了一個重要的道理。」': '5. "Last Saturday, I did something stupid, but it taught me an important lesson."',
  '5. 語言是否生動？（有修辭手法？句式有變化？）': '5. Is the language vivid?(Are there any rhetorical techniques? Are there changes in sentence structure?)',
  '6. 立意是否清晰？（有事件 → 衝突 → 感悟？）': '6. Is the intention clear?(Is there an incident → conflict → realization?)',
  '= 人物': '= character',
  '= 地點': '= location',
  '= 時間': '= time',
  '= 結果': '= result',
  '= 經過': '= passed',
  '= 起因': '= cause',
  'A. 「最後，我們和好了。這次吵架讓我明白到友誼很珍貴。」': 'A. "In the end, we reconciled. This quarrel made me realize that friendship is precious."',
  'A. 最後，我們一起收拾東西，依依不捨地離開沙灘。': 'A. Finally, we packed up our things together and reluctantly left the beach.',
  'A/B 對比：好開頭 vs 平庸開頭': 'A/B comparison: good start vs mediocre start',
  'B 明顯更好。A 是典型的「草草收場 + 硬加道理」，沒有畫面感。B 用具體的對話和動作來表達和好，讀者能「看到」那一刻的畫面，而且留白式地沒有直接說「我們和好了」，讓讀者自己去感受。': 'B is significantly better.A is a typical "hasty ending + forced reasoning", without any sense of picture.B uses specific dialogues and actions to express reconciliation, so that readers can "see" the scene at that moment, and does not directly say "we have reconciled" in a blank format, allowing readers to feel it themselves.',
  'B. 「那個星期五的下午，她終於走過來，把一本新書放在我桌上。『這本很好看，』她低著頭說，『看完⋯⋯要告訴我你覺得怎樣。』我愣了一下，然後笑了——這是我們這一個星期以來，說的第一句話。」': 'B. "On that Friday afternoon, she finally came over and put a new book on my desk. "This book is very good," she said with her head lowered. "After reading it... tell me what you think." I was stunned for a moment, and then smiled - this was the first thing we said in a week."',
  'B. 上星期日，我和家人到淺水灣游泳。': 'B. Last Sunday, my family and I went swimming in Repulse Bay.',
  'C. 期間，我們還堆了一座很大的沙城堡。': 'C. During this period, we also built a large sand castle.',
  'D. 到達後，我們先換上泳衣，然後衝進清涼的海水。': 'D. Upon arrival, we changed into our swimsuits and then jumped into the cool water.',
  '© 2026 記敘文增潤寫作教材 · 僅供教學使用': '© 2026 Narrative Enrichment Writing Textbook · For teaching purposes only',
  '— 故事有頭有尾，不會戛然而止': '— The story has a beginning and an end, and will not end abruptly',
  '— 看完後還會繼續思考': '— I will continue to think about it after reading it',
  '— 給讀者一個繼續閱讀的理由': '— Give readers a reason to keep reading',
  '— 被故事的核心意義打動': '— Moved by the core meaning of the story',
  '— 讓讀者想繼續看下去': '— Make readers want to keep reading',
  '— 讓讀者知道這是一篇什麼風格的文章': '— Let readers know what style of article this is',
  '• 主題三步法完整：事件 → 衝突 → 成長': '• Complete three-step thematic approach: Incident → Conflict → Growth',
  '• 有感悟：做對的事可能有代價，但值得': '• Feelings: Doing the right thing may come at a cost, but it’s worth it',
  '• 有衝突：友誼 vs 原則': '• There is conflict: friendship vs principles',
  '• 有轉折：好朋友的表情變化': '• There is a twist: the expressions of good friends change',
  '• 沒有衝突，沒有轉折': '• No conflict, no twists and turns',
  '• 結尾是空洞的道德口號': '• Ends with an empty moral slogan',
  '• 讀者看完沒有任何感覺': '• Readers don’t feel anything after reading it',
  '• 選材平庸，千篇一律的「拾金不昧」故事': '• The selection of materials is mediocre and the same story of "finding money but not knowing it"',
  '• 選材獨特：不寫俗套的「好事」，寫道德兩難': '• Unique selection of material: Don’t write about clichéd “good things”, but write about moral dilemmas',
  '→ 優點：真實、有衝突、有深度、寫出了人性的複雜': '→ Advantages: Reality, conflict, depth, and the complexity of human nature',
  '→ 結構：具體動作（攀、縮）+ 身體狀態描寫（肥胖）+ 整體印象（努力的樣子）': '→ Structure: specific actions (climbing, retracting) + description of body condition (obesity) + overall impression (looking like trying hard)',
  '→ 適合抒情、描寫場景、營造平靜的氣氛': '→ Suitable for expressing emotions, describing scenes, and creating a calm atmosphere',
  '→ 適合緊張時刻、動作描寫、製造懸念': '→ Suitable for tense moments, action description, and creating suspense',
  '⚡ 考試急救包（考前 10 分鐘速讀）': '⚡Exam First Aid Kit (10 minutes of quick reading before the exam)',
  '✅ 五感豐富、有內心獨白、有情感轉折、對話生動': '✅ Rich five senses, inner monologue, emotional transitions, and vivid dialogues',
  '✅ 動作分解（80 字）': '✅ Action breakdown (80 words)',
  '✅ 感悟昇華式。從比賽結果轉移到自我成長，有深度。': '✅ Feel the sublimation style.There is depth in moving from game results to self-growth.',
  '✅ 成功要素：': '✅ Success factors:',
  '✅ 文學語言': '✅ Literary language',
  '✅ 獨特選材（真實動人）': '✅ Unique selection of materials (real and touching)',
  '✅ 留白想像式。用一個具體的動作收尾，情感含蓄但有力。': '✅ Leave blank space for imagination.End with a specific action, which is emotionally subtle but powerful.',
  '✅ 精彩版': '✅ Wonderful version',
  '✅ 記敘文自評檢核表（通用版）': '✅ Narrative self-assessment checklist (general version)',
  '✋ 觸覺': '✋ Tactile',
  '✋ 觸覺（摸到什麼）：': '✋ Touch (what you touch):',
  '✋ 觸覺：後面的同學不停地推擠，我的書包被擠得貼在背上，汗水把校服黏在皮膚上。': '✋ Touch: The classmates behind me kept pushing and pushing, and my schoolbag was pressed against my back, and the sweat stuck the school uniform to my skin.',
  '✨ 語言': '✨ Language',
  '❌ 一句帶過': '❌ Pass it by one sentence',
  '❌ 偏離主題': '❌ Off topic',
  '❌ 問題分析：': '❌ Problem analysis:',
  '❌ 學生腔': '❌ Student accent',
  '❌ 平庸版': '❌ mediocre version',
  '❌ 普通選材（千篇一律）': '❌ Ordinary material selection (the same)',
  '❌ 無限延伸': '❌ Infinite extension',
  '❌ 硬加道理': '❌ Forced reasoning',
  '❌ 硬加道理。空洞的勵志口號，沒有具體的感悟。': '❌ Imposing truth.Empty motivational slogans without concrete insights.',
  '❌ 空洞、缺乏細節、只有「做了什麼」沒有「怎樣做的」和「感受如何」': '❌ Empty, lack of details, only “what was done” without “how” and “how it felt”',
  '❌ 草草收場': '❌ Ending hastily',
  '❌ 草草收場。太平淡，讀者沒有任何回味。': '❌ Ended hastily.It\'s too bland and the reader has no aftertaste.',
  '。」（聽覺 → 味覺）': '."(Hearing → Taste)',
  '。」（視覺 → 觸覺）': '."(Visual → Touch)',
  '。一個好結尾能讓讀者：': '.A good ending allows readers to:',
  '。一個好開頭能做到三件事：': '.A good beginning can do three things:',
  '《那一刻，我長大了》': '"At that moment, I grew up"',
  '「『你真的要去嗎？』媽媽的聲音在背後響起。我轉過身，看到她的眼神中有擔憂，也有不捨。」': '"\'Are you really going?\' Mom\'s voice sounded from behind. I turned around and saw worry and reluctance in her eyes."',
  '「『萬一忘詞怎麼辦？』這個念頭在腦中盤旋。『他們會笑我嗎？』」': '"\'What if I forget my words?\' This thought swirled in my mind. \'Will they laugh at me?\'"',
  '「不行。」我把字條推回去。我看到她的表情變了——先是驚訝，然後是受傷，最後是冷冷的。她再也沒有看我一眼。': '"No." I pushed the note back.I saw her expression change - first surprised, then hurt, then cold.She never looked at me again.',
  '「什麼？真的嗎？！」坐在前排的小明整個人跳了起來。': '"What? Really?!" Xiao Ming, who was sitting in the front row, jumped up.',
  '「今天天氣很熱，我流了很多汗。」': '"It\'s very hot today and I sweat a lot."',
  '「今天很開心，我期待下一次，還有下下一次⋯⋯」': '"I\'m very happy today, I\'m looking forward to the next time, and the next time..."',
  '「今天的天氣很好，我的心情也很好，大家也很好。」': '"The weather is nice today, I\'m in a good mood, and everyone is nice too."',
  '「他停下了腳步。轉過身來。看著我。沒有說話。」': '"He stopped. Turned around. Looked at me. No words."',
  '「他哭了。」（3 個字）': '"He cried." (3 words)',
  '「他很生氣地走了。」（8 個字）': '"He walked away angry." (8 words)',
  '「他用兩手攀著上面，兩腳再向上縮；他肥胖的身子向左微傾，顯出努力的樣子。」': '"He clung to it with both hands and retracted his feet upwards; his fat body leaned slightly to the left, showing that he was working hard."',
  '「他的笑聲大得': '"His laugh was so loud',
  '「他踮起腳尖，一隻手扶著櫃子的邊緣，另一隻手努力向上伸；他小小的身子向右微微傾斜，額頭上滲出了細細的汗珠，顯出拼命想達到的樣子。」': '"He stood on tiptoes, holding the edge of the cabinet with one hand, and trying hard to reach up with the other hand; his small body tilted slightly to the right, and there were thin beads of sweat on his forehead, showing that he was desperately trying to achieve it."',
  '「你有沒有試過看一本書，第一段就讓你很想繼續看下去？你還記得那第一段是怎樣的嗎？」': '"Have you ever read a book and the first paragraph made you want to keep reading? Do you remember what that first paragraph was like?"',
  '「你有沒有試過讀一篇文章，覺得某個句子特別美、特別有力？你還記得那個句子用了什麼技巧嗎？」': '"Have you ever tried to read an article and felt that a certain sentence was particularly beautiful and powerful? Do you still remember what techniques were used in that sentence?"',
  '「你知道我有多擔心你嗎？」媽媽的聲音在顫抖。': '"Do you know how worried I am about you?" Mom\'s voice was trembling.',
  '「你覺得一篇好的記敘文，結尾應該帶給讀者什麼感覺？你有沒有看過讓你印象深刻的故事結局？」': '"What do you think a good narrative should make the reader feel at the end? Have you ever seen a story ending that impressed you?"',
  '「你覺得兩篇同樣題目的文章，為什麼一篇讓人印象深刻，另一篇卻看完就忘了？差別在哪裡？」': '"Why do you think there are two articles with the same title? One is impressive, but the other is forgotten after reading it? What is the difference?"',
  '「你覺得精彩版用了什麼技巧，讓它比平庸版好看這麼多？」': '"What techniques do you think the wonderful version uses to make it look so much better than the mediocre version?"',
  '「你還記得上次寫的記敘文，老師給了什麼評語嗎？你覺得一篇好的記敘文，最重要的是什麼？」': '"Do you still remember the teacher\'s comments on the narrative essay you wrote last time? What do you think is the most important thing about a good narrative essay?"',
  '「借我抄一下吧，就這一次。」小藍把字條推到我的桌上。數學測驗還剩十分鐘，最後那道應用題像一座大山一樣擋在眼前。': '"Let me copy it, just this once." Xiao Lan pushed the note onto my desk.There are ten minutes left for the math test, and the last word question is blocking my eyes like a big mountain.',
  '「優秀版用了我們學過的哪些技巧？你可以從結構、描寫、開頭結尾、修辭、立意這六個層面來分析嗎？」': '"What techniques did we learn in the excellent version? Can you analyze it from the six levels of structure, description, beginning and end, rhetoric, and conception?"',
  '「光陰似箭，日月如梭」': '"Time flies like an arrow, and the sun and moon fly by like a shuttle."',
  '「全班都在笑，只有他一個人，安靜地坐在角落。」（用熱鬧襯托孤獨）': '"The whole class is laughing, but he is the only one, sitting quietly in the corner." (Use liveliness to contrast loneliness)',
  '「公園裡的花很美，有很多顏色。」': '"The flowers in the park are beautiful and come in many colors."',
  '「原來我以為今天是我來『幫助』他們的。但當我握著陳婆婆那雙滿布皺紋的手時，我才發現——是她們，用一生的故事，幫助了我這個不曾經歷風雨的少年，看到了一個更廣闊的世界。」': '"I thought I was here to \'help\' them today. But when I held Granny Chen\'s wrinkled hands, I realized that it was them who, with their life stories, helped me, a young man who had never experienced hardships, to see a broader world."',
  '「各位同學，我有一個重要的消息要宣布。」張老師走進課室，臉上掛著神秘的笑容。': '"Dear students, I have important news to announce." Teacher Zhang walked into the classroom with a mysterious smile on his face.',
  '「同一個故事，用不同的開頭會有完全不同的感覺。我們來看看同一篇文章的四種開頭。」': '"The same story will have completely different feelings with different beginnings. Let\'s take a look at four kinds of beginnings for the same article."',
  '「呯！」發令槍響了。第一棒的大明如箭一般衝了出去，順利地把棒交到我手上。': '"Bang!" The starting gun sounded.Daming, who was the first to bat, rushed out like an arrow and handed the baton smoothly to my hand.',
  '「哨聲響起的那一刻，我的心跳像擂鼓一樣砰砰作響。手心滲出了冷汗，雙腿像灌了鉛一樣沉重。『冷靜！你可以的！』我在心裡不停地對自己說。」（比喻 + 內心獨白）': '"The moment the whistle sounded, my heart beat like a drum. Cold sweat oozed from my palms, and my legs felt as heavy as lead. \'Calm down! You can do it!\' I kept saying to myself in my heart." (Metaphor + inner monologue)',
  '「在整片黑暗的天空中，那顆星顯得格外明亮。」（用黑暗襯托光明）': '"In the entire dark sky, that star looks particularly bright." (Use darkness to set off light)',
  '「夕陽把天空染成了一片橙紅色的海洋，雲朵像棉花糖一樣飄浮在其中，微風輕輕吹過，帶來了一天中最後一絲溫暖。」': '"The sunset dyed the sky into a sea of ​​orange-red, with clouds floating in it like cotton candy, and the gentle breeze blew by, bringing the last trace of warmth of the day."',
  '「大雨如瀑布般傾瀉而下，操場上的籃球架在雨幕中模糊成一個灰色的影子。我站在校門口的屋簷下，看著雨水在腳邊濺起一朵朵水花⋯⋯」': '"Heavy rain poured down like a waterfall, and the basketball stand on the playground blurred into a gray shadow in the rain curtain. I stood under the eaves of the school gate, watching the rain splashing water around my feet..."',
  '「天黑了。」': '"It\'s getting dark."',
  '「太陽像一個大火爐，把大地烤得滾燙。空氣中沒有一絲風，汗水像小溪一樣從額頭流下來，校服貼在背上，又濕又黏。」（比喻 + 觸覺）': '"The sun is like a big furnace, scorching the earth. There is no wind in the air, sweat flows from the forehead like a stream, and the school uniform sticks to the back, wet and sticky." (metaphor + touch)',
  '「她的聲音': '"Her voice',
  '「她站在門口，張了張嘴，卻什麼也沒說。最後，她只是輕輕地，把門關上了。」': '"She stood at the door and opened her mouth, but didn\'t say anything. In the end, she just closed the door gently."',
  '「如果你只有一天的生命，你會做什麼？這個問題，我在小六那年找到了答案。」': '"If you only had one day to live, what would you do? I found the answer to this question when I was in Primary 6."',
  '「如果你要告訴朋友一件很有趣的事，你會怎麼說？只說『今天發生了一件有趣的事』，還是會詳細地描述過程？」': '"If you were to tell a friend something interesting, what would you say? Just say, \'An interesting thing happened today,\' or would you describe the process in detail?"',
  '「如果這篇文章用倒敘來寫，你會把哪一段放在最開頭？」': '"If this article were written in flashback, which paragraph would you put at the beginning?"',
  '「就這樣，這一天結束了。」': '"That\'s it, the day is over."',
  '「從緊張到放鬆、從害怕到勇敢。當我看到老師鼓勵的眼神時，我忽然覺得⋯⋯」': '"From nervousness to relaxation, from fear to bravery. When I saw the teacher\'s encouraging eyes, I suddenly felt..."',
  '「恭喜你獲得亞軍！」當評審宣佈結果的那一刻，我簡直不敢相信自己的耳朵。我站在台上，捧著獎盃，腦海中卻浮現起今天早上的一幕幕——': '"Congratulations on winning second place!" When the judges announced the results, I couldn\'t believe my ears.I stood on the stage, holding the trophy, but the scenes from this morning came to my mind——',
  '「我們一起來讀這篇短文。你一邊讀，一邊在心裡找出六個要素在哪裡。」': '"Let\'s read this passage together. As you read, mentally identify the six elements."',
  '「我們來看兩篇同題文章。題目一樣，但一篇看完就忘了，另一篇會讓你想很多。差別到底在哪裡？」': '"Let\'s look at two articles with the same title. The title is the same, but one will be forgotten after reading it, while the other will make you think a lot. What is the difference?"',
  '「我們來讀兩篇文章，同樣的事件，一篇像白開水，一篇像濃湯。你來找找濃湯版多了什麼？」': '"Let\'s read two articles, the same incident, one is like boiled water, and the other is like thick soup. What are you looking for in the thick soup version?"',
  '「我們來讀幾篇文章的結尾，看看哪個讓你有感覺，哪個讓你覺得『就這樣而已？』」': '"Let\'s read the endings of a few articles and see which one makes you feel something, and which one makes you think, \'That\'s it?\'"',
  '「我們來讀讀兩位大作家的文字。看看他們用了什麼技巧，讓文字變得這麼有力量。」': '"Let\'s read the words of two great writers. Let\'s see what techniques they used to make their words so powerful."',
  '「我們班——在校際比賽中——拿了冠軍！」她的聲音愈來愈高，最後兩個字幾乎是喊出來的。': '"Our class - won the championship in the inter-school competition!" Her voice became higher and higher, and the last two words were almost shouted.',
  '「我在長長的走廊上奔跑，心跳快得像要從胸口衝出來，每一步都踩在時間的刀刃上。終於，我推開了門。他不在。」': '"I ran down the long corridor, my heart beating so fast that it felt like it was about to rush out of my chest. Every step I took was stepping on the blade of time. Finally, I opened the door. He was not there."',
  '「我很累，很想睡覺。」': '"I\'m very tired and want to sleep."',
  '「我很緊張。」': '"I\'m very nervous."',
  '「我很開心，非常開心。」': '"I\'m very happy, very happy."',
  '「我的心像一隻剛出籠的小鳥，輕飄飄地快要飛起來了。」': '"My heart is like a bird just out of the cage, so light that it\'s about to fly."',
  '「我看見他戴著黑布小帽，穿著黑布大馬褂，深青布棉袍，蹣跚地走到鐵道邊，慢慢探身下去，尚不大難。可是他穿過鐵道，要爬上那邊月台，就不容易了。他用兩手攀著上面，兩腳再向上縮；他肥胖的身子向左微傾，顯出努力的樣子。」': '"I saw him wearing a black cloth cap, a large black cloth mandarin jacket, and a dark blue cloth cotton robe. He staggered to the side of the railway and slowly leaned down. It was not too difficult. But it was not easy for him to cross the railway and climb up to the platform over there. He clung to the top with both hands and retracted his feet; his fat body leaned slightly to the left, showing that he was trying hard."',
  '「我要不要讓座呢？」我心裡猶豫著。「今天上了一整天課，腿也很累啊⋯⋯但婆婆看起來比我更需要這個座位⋯⋯」（💭內心獨白）': '"Should I give up my seat?" I hesitated in my mind."I have been in class all day today, and my legs are very tired...but my mother-in-law seems to need this seat more than me..." (💭Internal monologue)',
  '「探身下去 → 攀著上面 → 兩腳上縮 → 身子微傾」— 朱自清把父親爬月台這個動作分解成連續步驟，像電影慢鏡頭，讓讀者仿佛親眼看到。': '"Lean down → Climb up → Pull your legs up → Lean slightly" - Zhu Ziqing breaks down his father\'s action of climbing the platform into consecutive steps, like a slow motion movie, allowing readers to see it with their own eyes.',
  '「接下來，有請六年級的李小明同學上台演講。」主持人的聲音在禮堂中迴盪。我的心跳瞬間加速，手心開始冒汗。我能做到嗎？': '"Next, I invite Li Xiaoming, a sixth-grade student, to give a speech." The host\'s voice echoed in the auditorium.My heart beat faster and my palms began to sweat.can i do it?',
  '「故鄉的風箏時節，是春二月，倘聽到沙沙的風輪聲，仰頭便能看見一個淡墨色的蟹風箏或嫩藍色的蜈蚣風箏。⋯⋯但我是向來不愛放風箏的，不但不愛，並且嫌惡它，因為我以為這是沒出息孩子所做的玩藝。」': '"The kite season in my hometown is in the spring of February. If you hear the rustling of the wind wheel, you can look up and see a light ink crab kite or a tender blue centipede kite. But I have never liked flying kites. Not only do I not love it, I also hate it, because I think it is a toy made by unpromising children."',
  '「文學語言和學生腔最大的分別是什麼？你能用一句話總結嗎？」': '"What is the biggest difference between literary language and student accent? Can you sum it up in one sentence?"',
  '「暮色像一層薄薄的黑紗，無聲無息地蓋住了整個城市。」': '"Twilight is like a thin layer of black veil, covering the whole city silently."',
  '「月亮': '"moon',
  '「比賽開始了，我很緊張。」': '"The game has started and I\'m very nervous."',
  '「沙沙的風輪聲」— 不只寫看到的，還寫聽到的。': '"The sound of rustling wind wheels" - not only write what you see, but also what you hear.',
  '「淡墨色」、「嫩藍色」— 用具體顏色描寫風箏，視覺感強。': '"Light ink color", "tender blue" - use specific colors to describe the kite, which has a strong visual sense.',
  '「然後我起床，然後我刷牙，然後我吃早餐，然後我出門。」': '"Then I get up, then I brush my teeth, then I eat breakfast, and then I go out."',
  '「然後病」': '"Then I got sick"',
  '「生日蛋糕上的蠟燭一根根地燃燒著，溫暖的燭光映在每個人的臉上。但今年的生日，我卻在燭光背後看到了一樣我從未發現的東西⋯⋯」': '"The candles on the birthday cake were burning one by one, and the warm candlelight reflected on everyone\'s face. But this year\'s birthday, I saw something behind the candlelight that I had never seen before..."',
  '「當我打開那個信封，裡面只有一張紙條，上面寫著：『其實，一直幫助你的人，不是別人，就是你自己。』」': '"When I opened the envelope, there was only a note inside, which said: \'Actually, the person who has been helping you is no one else but yourself.\'"',
  '「當我接過獎盃的那一刻，腦海中浮現起三個月來的艱苦訓練⋯⋯」→ 回頭寫訓練過程': '"The moment I received the trophy, the three months of hard training came to mind..." → Write back about the training process',
  '「當然是真的！」張老師笑著說，「我也為你們感到驕傲！你們的努力沒有白費。」': '"Of course it\'s true!" Teacher Zhang said with a smile, "I\'m proud of you too! Your efforts have not been in vain."',
  '「眼皮像被千斤重的石頭壓著，每抬一步都像在泥沼中前行。」': '"My eyelids felt like they were pressed down by a thousand-jin stone, and every step I took was like walking through a quagmire."',
  '「老師很生氣，我們都很害怕。」': '"The teacher was angry and we were all scared."',
  '「豐滿版用了哪些技巧？你能找出多少個『五感描寫』的例子？心理描寫用了哪幾個層次？」': '"What techniques were used in the plump version? How many examples of "five senses description" can you find? What levels of psychological description were used?"',
  '「蹣跚」、「探身」、「攀」、「縮」、「傾」— 每個動詞都經過精心挑選。': '"Stagger", "lean out", "climb", "shrink", "lean" - every verb has been carefully selected.',
  '「這件事告訴我們做人要誠實，誠實是一種美德，我們都應該做誠實的人。」': '"This incident tells us that we must be honest. Honesty is a virtue. We should all be honest people."',
  '「這個蛋糕很好吃，我很喜歡。」': '"This cake is delicious, I like it very much."',
  '「那個暑假，': '"That summer vacation,',
  '「那天之後，我終於明白——真正的勇敢，不是在於不跌倒，而是在於跌倒之後，還能爬起來繼續向前走。」': '"After that day, I finally understood that true bravery does not lie in not falling, but in being able to get up and keep moving forward after falling."',
  '「那天，我做了一件至今難忘的事。」': '"That day, I did something I will never forget."',
  '「那幅畫的紅色': '"The red color of that painting',
  '「陽光穿過窗簾的縫隙，在地板上畫出一道金色的線。微風吹進來，帶來茉莉花的香氣。那個下午，一切都很平靜——直到電話鈴聲響起。」': '"The sunlight passed through the gap in the curtains and drew a golden line on the floor. The breeze blew in, bringing the fragrance of jasmine. That afternoon, everything was peaceful - until the phone rang."',
  '「風中傳來': '"Coming in the wind',
  '一、為什麼開頭那麼重要？': '1. Why is the beginning so important?',
  '一、結尾為什麼重要？': '1. Why is the ending important?',
  '一、記敘文的六要素': '1. Six elements of narrative writing',
  '一位老人在公園裡慢慢地跑步': 'An old man jogging slowly in the park',
  '一個小孩努力地伸手去拿高處的糖果罐': 'A child struggles to reach for a high candy jar',
  '一個銀色的盤子，掛在夜空中。」': 'A silver plate hanging in the night sky."',
  '一年一度的學校運動會舉行在即': 'The annual school sports meeting is about to be held',
  '三、如何選擇敘事順序？': '3. How to choose the narrative order?',
  '三、結尾四大忌': '3. Four Taboos at the End',
  '上個月，我第一次在全校師生面前演講。那三分鐘的經歷，至今仍然深深烙印在我的記憶中。': 'Last month, I gave a speech in front of the entire school for the first time.Those three minutes of experience are still deeply imprinted in my memory.',
  '上早已熱鬧非凡，彩旗在風中飄揚，一年一度的運動會即將開始。': 'The sky is already bustling with activity, colorful flags are fluttering in the wind, and the annual sports meeting is about to begin.',
  '上星期三，我們班有一次數學測驗。我溫習了很久，希望可以拿到好成績。': 'Last Wednesday, our class had a math test.I have been studying for a long time, hoping to get good grades.',
  '上星期五、一個晴朗的早晨': 'Last Friday, a sunny morning',
  '上星期五的清晨': 'last friday morning',
  '不只寫「我很緊張」，而要寫出緊張時腦中的聲音，以及緊張如何逐漸變化。這樣讀者才能「走進」你的心裡。': 'Don\'t just write "I\'m nervous," but write about the voice in your head when you\'re nervous and how the tension gradually changes.This way readers can "get into" your heart.',
  '不只寫「看到」的，調動全部感官來豐富畫面：': 'Don’t just write about what you “see”, but use all your senses to enrich the picture:',
  '不只寫事件': 'Don’t just write about events',
  '不只是寫「發生了什麼」，更要寫「這件事如何改變了我」。沒有感悟的記敘文，只是流水帳；有感悟的記敘文，才是好文章。': 'Don’t just write “what happened”, but also “how this changed me”.A narrative without insights is just a running account; a narrative with insights is a good article.',
  '不要草草收場': 'Don\'t end things hastily',
  '不要選「最安全」的事件，而要選「最有感觸」的事件。好的選材通常具備：有矛盾、有轉折、有個人特色。': 'Don’t choose the “safest” event, but choose the “most touching” event.Good material selection usually has: contradictions, transitions, and personal characteristics.',
  '主題提煉三步法': 'Three-step method for refining themes',
  '主題：《我和好朋友吵架了》（文章主體省略，只展示不同結尾）': 'Topic: "I had a fight with a good friend" (the main body of the article is omitted, only different endings are shown)',
  '主題：《第一次上台演講》— 四種開頭對比': 'Topic: "First Speech on Stage" - Comparison of Four Beginnings',
  '乾癟版（~100字）': 'Dry version (~100 words)',
  '事件 → 衝突/轉折 → 感悟/成長': 'Event → Conflict/Turning → Enlightenment/Growth',
  '二、三種敘事順序': '2. Three Narrative Orders',
  '二、四種結尾策略': '2. Four Ending Strategies',
  '二、四種開頭策略': '2. Four opening strategies',
  '五感描寫法': 'Five senses description method',
  '人物回憶': 'Character memories',
  '人際故事、家庭記敘、衝突事件。': 'Interpersonal stories, family narratives, conflict events.',
  '今天在上學途中，我看到地上有一個銀包。我把它撿起來，看到裡面有一些錢和一張身份證。我想失主一定很著急，所以我把銀包交給了附近的警察。警員叔叔稱讚我是一個好孩子。我很開心，因為我做了一件好事。': 'On my way to school today, I saw a wallet on the ground.I picked it up and saw some money and an ID card inside.I thought the owner must be very anxious, so I handed the wallet to the nearby police.The police uncle praised me as a good boy.I\'m happy because I did something good.',
  '今天放學後，我坐巴士回家。車上很多人，很擠。後來有一位老婆婆上了車，她看起來很累的樣子。我想到老師教我們要讓座給有需要的人，於是我站起來把座位讓給老婆婆。她對我笑了笑，我覺得很開心。': 'After school today, I took the bus home.There were many people on the bus and it was very crowded.Later, an old woman got on the bus. She looked very tired.I thought that the teacher taught us to give up our seats to those in need, so I stood up and gave my seat to the old lady.She smiled at me and I felt happy.',
  '今天早上，媽媽帶我來參加鋼琴比賽。走進比賽場地時，我的手心全是汗，心跳快得像要從胸口跳出來⋯⋯（之後接回順敘內容）': 'This morning, my mother took me to participate in the piano competition.When I walked into the competition venue, my palms were all sweaty, and my heart was beating so fast that it felt like it was about to jump out of my chest... (Retrieve the following content later)',
  '今天早上，媽媽帶我去參加鋼琴比賽。我緊張地走進比賽場地，手心全是汗。輪到我上台時，我的腦中一片空白。但當我坐下，手指觸碰到琴鍵的那一刻，所有緊張都消失了。我順利完成演奏，最後還拿到了亞軍。': 'This morning, my mother took me to a piano competition.I walked into the competition venue nervously, my palms all sweaty.When it was my turn to take the stage, my mind went blank.But the moment I sat down and touched the keys with my fingers, all the nerves disappeared.I successfully completed the performance and finally won the second place.',
  '今天是我的生日，我很開心，因為媽媽買了一個很大的蛋糕給我。': 'Today is my birthday. I am very happy because my mother bought me a big cake.',
  '他的眼眶先是一紅，嘴唇微微顫抖。然後，第一滴眼淚從眼角滑落，順著臉頰流下來。他低下頭，肩膀開始輕輕抽動，接著越抖越厲害，終於忍不住發出了壓抑的哭聲。': 'His eyes turned red at first, and his lips trembled slightly.Then, the first tear slipped from the corner of his eye and flowed down his cheek.He lowered his head, and his shoulders began to twitch slightly, then became more and more violent, and finally he couldn\'t help but let out a suppressed cry.',
  '他的臉色刷地一下變了，眉頭緊緊地皺在一起。他沒有說話，只是狠狠地瞪了我一眼——那眼神冷得像冬天的冰水。他的手緊緊握成拳頭，指節都發白了。然後，他猛地轉過身去，腳步又重又急，每一步都像要把地板踩碎一樣。門「砰」的一聲巨響，他的身影消失在走廊的盡頭。': 'His expression suddenly changed, and his brows knitted together tightly.He didn\'t speak, but gave me a fierce look - his eyes were as cold as ice water in winter.His hands were clenched into fists until his knuckles turned white.Then, he turned around suddenly, his steps heavy and fast, as if he was crushing the floor with each step.There was a loud bang on the door, and his figure disappeared at the end of the corridor.',
  '以一句對話開始，讓人物立刻「出場」。': 'Start with a line of dialogue and let the character "appear" immediately.',
  '以下 4 個結尾，請判斷它是「好結尾」還是「有問題的結尾」，並說出理由：': 'For the following 4 endings, please decide whether it is a "good ending" or a "problematic ending" and give your reasons:',
  '以下 5 句都是「學生腔」。請你選擇其中 2 句來潤色，用上今天學到的修辭技巧：': 'The following 5 sentences are all "student accent".Please choose 2 of the sentences to polish and use the rhetorical skills you learned today:',
  '以下兩個開頭都太平淡了，請選擇其中一個，用': 'The following two beginnings are too bland, please choose one of them and use',
  '以下句子次序被打亂了，請把它們按正確順序排列：': 'The following sentences are out of order, please put them in the correct order:',
  '以下是一段場景的「骨架」，請你為它補入': 'The following is the "skeleton" of a scene, please fill it in',
  '以下是一段順敘的短文，請你把它改寫成': 'The following is a narrated passage. Please rewrite it as',
  '以下是文章的主體摘要，請為它選擇最適合的結尾：': 'The following is the main summary of the article. Please choose the most suitable ending for it:',
  '以下是文章的主體（已經有開頭和經過），請你為它寫一個結尾。試試用': 'The following is the main body of the article (already has a beginning and ending), please write an ending for it.Try it',
  '以下是朱自清《背影》中的經典句式結構，請模仿這個結構，換一個主題來寫：': 'The following is the classic sentence structure in Zhu Ziqing\'s "Back View". Please imitate this structure and write on a different topic:',
  '以下段落所有對話都是用': 'All dialogue in the following paragraphs uses',
  '以場景或畫面開頭的文章、抒情記敘。': 'Articles and lyrical narratives that begin with a scene or picture.',
  '以對話開場，立即把讀者帶入情境。有臨場感，展現了人物的緊張心情。': 'Open with dialogue and immediately bring the reader into the situation.It has a sense of presence and shows the nervousness of the characters.',
  '仿寫主題（二選一）：': 'Imitation theme (choose one of two):',
  '何時發生？': 'When does it happen?',
  '你做出了什麼選擇？這個選擇帶來了什麼後果？': 'What choices did you make?What are the consequences of this choice?',
  '你有沒有經歷過一件讓你突然「不再是小孩子」的事？': 'Have you ever experienced something that suddenly made you "no longer a kid"?',
  '你有沒有試過，雙腿不受控制地發抖，卻還要裝作若無其事地站在台上？那種感覺，我在小六第一次演講時，真真切切地經歷了一次。': 'Have you ever tried to stand on stage pretending to be nonchalant while your legs were shaking uncontrollably?I really experienced that feeling when I gave my first speech at Xiaoliu.',
  '你的答案': 'your answer',
  '你認為以下哪個結尾最好？': 'Which of the following endings do you think is the best?',
  '來自哪個單元': 'From which unit',
  '例子（《運動會的一天》）': 'Example ("A Day at the Sports Meet")',
  '例子（不要這樣寫！）': 'Example (don’t write like this!)',
  '例子（主題：上台緊張）': 'Example (Topic: Nervousness about going on stage)',
  '例子：': 'example:',
  '例：題目《一件小事》': 'Example: Title "A Little Thing"',
  '修改建議': 'Modification suggestions',
  '修辭手法': 'rhetorical devices',
  '修辭與句式節奏': 'Rhetoric and sentence rhythm',
  '健步如飛、躡手躡腳、顫巍巍、大步流星': 'Walking like flying, tiptoeing, trembling, striding like a meteor',
  '傾盆大雨、毛毛細雨、煙雨濛濛、大雨滂沱': 'Downpour, drizzle, misty rain, heavy rain',
  '像蜜糖一樣甜': 'sweet as honey',
  '優秀版': 'Excellent version',
  '優點：': 'advantage:',
  '先展示高潮，製造懸念，吸引讀者': 'Show the climax first to create suspense and attract readers',
  '先把故事的結局或最精彩的部分放在開頭，再回頭敘述事件經過。': 'Put the ending or the most exciting part of the story at the beginning first, and then go back and narrate the events.',
  '全教材回顧：一篇好記敘文的六層檢查': 'Review of the entire textbook: Six-level inspection of a good narrative essay',
  '全班頓時安靜下來。': 'The whole class suddenly fell silent.',
  '兩種不同': 'two different',
  '六要素一個都不能少': 'None of the six elements can be missing',
  '六要素完整？敘事順序恰當？': 'Are the six elements complete?Is the narrative sequence appropriate?',
  '六要素完整？（時間、地點、人物、起因、經過、結果）': 'Are the six elements complete?(time, place, person, cause, process, result)',
  '六要素與敘事結構': 'Six elements and narrative structure',
  '分析：': 'analyze:',
  '刪掉多餘的「然後」，用不同連接詞或直接省略。': 'Delete the redundant "then", use different connectives or omit it altogether.',
  '刻意放大事物的特徵以突出效果': 'Deliberately magnify the characteristics of things to highlight the effect',
  '創作故事': 'Create a story',
  '動作分解術': 'action decomposition',
  '動作分解：': 'Action breakdown:',
  '原來自尊心是友誼的敵人；一句對不起比憋在心裡輕鬆得多': 'It turns out that self-esteem is the enemy of friendship; it is easier to say sorry than to hold it in your heart',
  '參考仿寫': 'Reference imitation',
  '參考仿寫（主題 2）：': 'Reference Imitation (Topic 2):',
  '參考填充': 'Reference fill',
  '參考填充：': 'Reference padding:',
  '參考擴寫': 'Reference extension',
  '參考擴寫：': 'Reference expansion:',
  '參考改寫': 'Reference rewritten',
  '參考改寫 A（懸念式）：': 'Reference rewrite A (suspense style):',
  '參考改寫 B（場景式）：': 'Reference rewrite B (scenario style):',
  '參考改寫（倒敘版）：': 'Reference rewritten (flashback version):',
  '參考改造': 'Reference transformation',
  '參考改造：': 'Reference transformation:',
  '參考潤色': 'Reference polish',
  '參考潤色：': 'Reference polish:',
  '參考答案：': 'Reference answer:',
  '參考答案：B → D → C → A': 'Reference answer: B → D → C → A',
  '參考結尾': 'end of reference',
  '參考結尾（感悟昇華式）：': 'Reference ending (emotional sublimation style):',
  '反轉式': 'Reversal',
  '受到觸動': 'touched',
  '句式節奏：長句與短句的配合': 'Sentence rhythm: the combination of long and short sentences',
  '台下響起熱烈的掌聲。我站在聚光燈下，看著觀眾席上爸爸媽媽驕傲的笑容，忽然覺得——輸贏已經不重要了。重要的是，我終於做到了。': 'There was warm applause from the audience.I stood under the spotlight, looking at the proud smiles of my parents in the audience, and suddenly felt that winning or losing was no longer important.The important thing is, I finally did it.',
  '同一事件《一次考試》，兩種開頭寫法：': 'The same event "An Examination" can be written in two ways:',
  '同一個事件：': 'Same event:',
  '同一個題目，為什麼有人寫得特別？— 選材角度決定高度': 'Why does someone write on the same topic in a special way?— The angle of material selection determines the height',
  '同一篇文章，四種不同結尾': 'The same article, four different endings',
  '同題異作對比：《一件小事》': 'Comparing different works with the same title: "A Little Thing"',
  '名家片段賞析一：朱自清《背影》（節選）': 'Appreciation of Famous Fragments 1: Zhu Ziqing\'s "Back View" (Excerpt)',
  '名家片段賞析二：魯迅《風箏》（節選）': 'Appreciation of Famous Fragments 2: Lu Xun\'s "Kite" (Excerpt)',
  '吸引注意': 'attract attention',
  '呼應式': 'responsive',
  '單元一': 'Unit 1',
  '單元一：記敘文的骨架': 'Unit 1: The skeleton of narrative',
  '單元三': 'Unit 3',
  '單元三：豬肚 — 把事情寫具體': 'Unit 3: Pork Belly - Make things specific',
  '單元二': 'Unit 2',
  '單元二：鳳頭 — 寫一個抓人的開頭': 'Unit 2: Crested Head - Write a catchy beginning',
  '單元二：鳳頭 — 抓人的開頭': 'Unit 2: Crested Head - The Beginning of Arresting People',
  '單元五': 'Unit 5',
  '單元五：語言的打磨': 'Unit 5: Polishing the Language',
  '單元六': 'Unit 6',
  '單元六：從好到精': 'Unit 6: From good to great',
  '單元四': 'Unit 4',
  '單元四：豹尾 — 結尾的藝術': 'Unit 4: Leopard Tail - The Art of Ending',
  '四大常用修辭': 'Four Commonly Used Rhetoric',
  '四種結尾策略': 'Four closing strategies',
  '四種開頭策略': 'Four opening strategies',
  '圓滿落幕、曲終人散、意猶未盡': 'It ends successfully, the song ends and everyone disperses, but the meaning is still unfinished',
  '在哪裡發生？': 'Where does it happen?',
  '在巴士上讓座給老婆婆': 'Give up your seat to an old lady on the bus',
  '在老人院，我遇到了一位陳婆婆。她已經八十多歲了，行動不便，但記憶力出奇地好。她拉著我的手，給我講了很多她年輕時的故事——戰亂、逃難、來到香港從零開始⋯⋯說著說著，她忽然停了下來，眼眶紅了。': 'In the nursing home, I met Granny Chen.She is over eighty years old and has limited mobility, but her memory is surprisingly good.She held my hand and told me many stories about her youth - war, escape, coming to Hong Kong and starting from scratch... As she spoke, she suddenly stopped, her eyes red.',
  '在街上撿到錢包，交還給失主。失主很感激，說我是好孩子。': 'Pick up a wallet on the street and return it to the owner.The owner was very grateful and said I was a good boy.',
  '在順敘的過程中，暫時插入一段相關的回憶或背景說明，再回到主線繼續敘述。': 'In the process of narrating, temporarily insert a relevant memory or background description, and then return to the main line to continue the narrative.',
  '堅持，': 'persist in,',
  '場景式': 'scene style',
  '場景：學校的小食部，小息的時候。': 'Scene: The school snack bar, during recess.',
  '夜空中一個銀色的盤子。」': 'A silver plate in the night sky."',
  '太陽下山了，我們也該回家了。今天真是快樂的一天啊！': 'The sun has gone down and it\'s time for us to go home.Today is such a happy day!',
  '好結尾': 'good ending',
  '如何發生？（最詳細）': 'How does it happen?(most detailed)',
  '如果 ❌，需要改什麼？': 'If ❌, what needs to be changed?',
  '如火如荼、一波三折、峰迴路轉': 'In full swing, twists and turns, twists and turns',
  '婆婆轉過頭來，滿臉的皺紋擠成了一個慈祥的笑容：「謝謝你啊，小朋友。」她坐下的時候，長長地舒了一口氣。（👂聽）': 'The mother-in-law turned her head, and the wrinkles on her face squeezed into a kind smile: "Thank you, kid." When she sat down, she let out a long sigh of relief.(👂Listen)',
  '媽媽說她很擔心我。': 'Mom said she was worried about me.',
  '學校操場': 'school playground',
  '完成寫作後，請對照以下清單逐一檢查你的文章：': 'Once you\'ve finished writing, check your article against the following checklist:',
  '定下基調': 'set the tone',
  '容光煥發、垂頭喪氣、若有所思、目瞪口呆': 'Radiant, crestfallen, thoughtful, dumbfounded',
  '實戰練習': 'Practical exercises',
  '寫事 — 過程、轉折、高潮': 'Writing - process, transition, climax',
  '寫人 — 外表、動作、神態': 'Writing about people - appearance, actions, demeanor',
  '寫作提示：禮物不一定是實物。一份原諒、一個擁抱、一句話，都可以是禮物。': 'Writing tip: Gifts don’t have to be physical items.A forgiveness, a hug, a word can be a gift.',
  '寫作提示：聚焦一個轉變的瞬間。你從一個狀態變成另一個狀態的關鍵時刻。': 'Writing tip: Focus on a moment of transformation.The critical moment when you transition from one state to another.',
  '寫作提示：選一個你想改變的時刻。不只是後悔，更要寫出你從中學到了什麼。': 'Writing tip: Pick a moment when you wanted to change something.Not just regret it, but write about what you learned from it.',
  '寫作錦囊': 'Writing Tips',
  '寫出內心聲音': 'Write your inner voice',
  '寫出情緒的轉折，從 A 狀態變成 B 狀態': 'Write about the transition of emotion from state A to state B',
  '寫出矛盾點或轉變的關鍵時刻': 'Write about points of conflict or key moments of change',
  '寫出腦中在想什麼，用引號或自問自答': 'Write down what is on your mind, use quotation marks or ask yourself questions',
  '寫天黑': 'write dark',
  '寫完每一篇記敘文後，拿出這張清單自我檢查：': 'After you finish writing each narrative, check this list with yourself:',
  '寫情 — 喜怒哀樂': 'Writing emotions - joy, anger, sorrow and joy',
  '寫景 — 天氣、環境、氣氛': 'Scenery - weather, environment, atmosphere',
  '寫比賽中途 → 插入「我想起去年在同一場地落敗的經歷」→ 回到比賽': 'In the middle of writing about the game → insert "I remembered my experience of losing at the same venue last year" → return to the game',
  '寫法：': 'Writing method:',
  '寫清楚「發生了什麼」': 'Write clearly "what happened"',
  '寫的，非常沉悶。請你把全部對話改為': 'Written, very dull.Please change all conversations to',
  '寫這件事如何改變你': 'How did writing about it change you?',
  '寫運動會，結尾突然變成「所以我決定以後要好好讀書」。': 'When writing about a sports meeting, the ending suddenly changed to "So I decided to study hard in the future."',
  '寫開心': 'write happy',
  '對比展示：「乾癟版」vs「豐滿版」': 'Comparative display: "Dry version" vs "Plump version"',
  '對比襯托': 'Contrast',
  '對比：學生腔 vs 文學語言': 'Comparison: student accent vs literary language',
  '對答案': 'Right answer',
  '對話式': 'Conversational',
  '對話生動？（用了直接引語？不是全部間接？）': 'Lively dialogue?(Used direct quotation? Not all indirect?)',
  '對話穿插技巧': 'Conversation interweaving skills',
  '對話要推動情節，不只為對話而對話。每句對話都應該透露信息、展現性格、或製造衝突。': 'Dialogue should advance the plot, not just dialogue for the sake of dialogue.Every line of dialogue should reveal information, reveal character, or create conflict.',
  '小學六年級 · 拔尖進階 · 一對一補習適用': 'Sixth grade primary school · Top-notch advanced · One-to-one tutoring is applicable',
  '屬於哪種類型？': 'Which type does it belong to?',
  '巴士在顛簸的馬路上搖晃著前進，車廂裡擠滿了放學的學生和下班的上班族，空氣中混雜著汗水和雨後的潮濕氣味（👃嗅）。我緊緊抓著扶手，書包壓得肩膀隱隱作痛（✋觸）。': 'The bus swayed forward on the bumpy road. The carriage was crowded with students after school and office workers after get off work. The air was mixed with the smell of sweat and dampness after the rain (👃sniff).I clutched the armrest tightly, and my shoulders ached under the weight of my schoolbag (✋touch).',
  '常見語病診斷': 'Diagnosis of common speech disorders',
  '平淡，欠臨場感': 'Bland, lacking a sense of presence',
  '建議順序': 'Suggested order',
  '張老師走進課室，對我們說她有一個重要的消息要宣布。她說我們班在校際比賽中拿了冠軍。同學們聽完後都非常興奮，有人說不敢相信，有人說一定要好好慶祝。張老師說她也為我們感到驕傲。': 'Teacher Zhang walked into the classroom and told us that she had important news to announce.She said that our class won the championship in the inter-school competition.The students were very excited after hearing this. Some said they couldn\'t believe it, while others said they must celebrate.Teacher Zhang said she was also proud of us.',
  '後來你對這件事有什麼新的理解？': 'What new understanding did you gain about this matter later?',
  '從「不愛」到「嫌惡」，情感遞進。': 'From "dislike" to "dislike", the emotions progress.',
  '從一個具體的場景描寫開始，把讀者帶入情境。': 'Start with a specific description of the scene and bring the reader into the situation.',
  '從具體的事件中，歸納出一個更深刻的人生體悟。': 'From specific events, a more profound understanding of life can be summarized.',
  '心如刀割、泣不成聲、肝腸寸斷、黯然神傷': 'My heart is like a knife, I can\'t cry, my heart is broken, I feel sad',
  '心理描寫三層次': 'Three levels of psychological description',
  '心花怒放、喜上眉梢、欣喜若狂、樂不可支': 'Be elated, joyful, ecstatic, overjoyed',
  '忐忑不安、心驚膽戰、坐立不安、七上八下': 'Uneasy, frightened, restless, restless',
  '思考以下問題，幫助你找到獨特的選材角度：': 'Consider the following questions to help you find your unique perspective:',
  '情感層次：': 'Emotional level:',
  '感到完整': 'feel complete',
  '感悟昇華式': 'Sublimation of perception',
  '懸念式': 'Suspense',
  '成長故事、難忘經歷、有啟發性的事件。': 'Growth stories, unforgettable experiences, inspiring events.',
  '我、同學大明、班主任陳老師': 'Me, my classmate Daming, and my head teacher Chen',
  '我們班沒有拿到名次，但當我跑回班級隊伍時，迎接我的是雷鳴般的掌聲。班主任陳老師拍拍我的肩說：「你沒有放棄，這就是最好的成績。」': 'Our class didn\'t get a ranking, but when I ran back to the class team, I was greeted with thunderous applause.The head teacher, Teacher Chen, patted me on the shoulder and said, "You didn\'t give up. This is the best result."',
  '我和同學大明': 'My classmate Daming and I',
  '我和好朋友吵架了': 'I had a fight with a good friend',
  '我和好朋友因為借書的事情鬧翻了，整整一個星期沒有說話。這段時間裡，我看到她和別的同學一起玩，心裡很難受。我們的座位只隔了兩行，卻像隔了一道看不見的牆。': 'My good friend and I had a falling out over borrowing books, and we didn\'t speak for a whole week.During this time, I felt very sad when I saw her playing with other classmates.Our seats were only two rows apart, but it was like an invisible wall.',
  '我學會了': 'I learned',
  '我拼盡全力向前奔跑，耳邊只有風聲和同學的吶喊。就在轉彎的時候，我腳下一滑，整個人摔倒在跑道上。膝蓋傳來一陣刺痛，我幾乎想要放棄。但當我抬起頭，看到跑道旁同學們焦急的眼神，聽到他們大聲喊著我的名字，一股力量從心底湧起。我咬緊牙關，爬起來繼續向前跑。': 'I ran forward with all my strength, with only the sound of wind and the shouts of my classmates in my ears.Just as I was turning, my foot slipped and I fell onto the track.There was a sharp pain in my knees and I almost wanted to give up.But when I raised my head, saw the anxious eyes of my classmates beside the track, and heard them shouting my name, a surge of strength surged from the bottom of my heart.I gritted my teeth, got up and continued running forward.',
  '我最終把棒交到第三棒同學手中。': 'I finally handed the baton to the third battalion classmate.',
  '我發現自己也有錯，但要開口道歉太難了': 'I realized that I was at fault too, but it was too difficult to apologize.',
  '我的手心在冒汗。小藍是我從小學一年級就認識的好朋友，我們的書桌只隔了三十厘米——但這三十厘米，此刻像一道懸崖。': 'My palms are sweating.Xiao Lan is my good friend since the first grade of elementary school. Our desks are only thirty centimeters apart - but these thirty centimeters are like a cliff at the moment.',
  '我看著書桌上那張合照——那是我們去年一起去露營時拍的。照片中的我們笑得那麼燦爛。我拿起手機，猶豫了很久，最後還是按下了那串熟悉的號碼⋯⋯': 'I looked at the photo on the desk - it was taken when we went camping together last year.We are smiling so brightly in the photo.I picked up the phone, hesitated for a long time, and finally pressed the familiar number...',
  '把一個簡單的動作拆成連續的小步驟，像慢鏡頭一樣呈現：': 'Break a simple action into consecutive small steps and present them in slow motion:',
  '把一種感官的感受，用另一種感官來描述。打破感官的界限，創造新奇的表達。': 'Describe the feelings of one sense using another sense.Break the boundaries of the senses and create novel expressions.',
  '把下面這句簡單的敘述，用': 'Use the following simple description:',
  '把事物當作人來寫，賦予人的動作/情感': 'Write things as if they were people and give them human actions/emotions',
  '抒情文章、情感細膩的故事。': 'Lyrical articles, emotionally delicate stories.',
  '抒情記敘、回憶往事、描寫性強的文章。': 'Lyrical narratives, memories of past events, and highly descriptive articles.',
  '拉開序幕、萬事俱備、蓄勢待發': 'The curtain has been kicked off, everything is ready and ready to go',
  '按事件發生的先後次序來寫。特點是條理清晰，讀者容易跟上。': 'Write the events in the order they occurred.It is characterized by clear organization and easy for readers to follow.',
  '描寫技巧核心': 'Core description skills',
  '換詞：「今天天氣晴朗，我的心情格外暢快，同學們也都笑容滿面。」': 'Change the words: "The weather is sunny today, I am in a particularly happy mood, and my classmates are all smiling."',
  '搬家的貨車駛遠了。我沒有回頭，只是握緊了口袋裡那張和好朋友的合照。': 'The moving truck drove away.I didn\'t look back, I just held the photo with my good friends in my pocket.',
  '擴寫為 100 字以上：': 'Expand to 100 words or more:',
  '改寫：': 'rewrite:',
  '放學的鈴聲響了。她從我身邊走過，腳步放慢了一點——就那麼一秒鐘——然後繼續向前走。我看著她的背影消失在走廊盡頭。書包裡，那包她最愛吃的軟糖，還沒有送出去。': 'The school bell rang.She walked past me, slowed her pace a little - just for a second - and then kept walking.I watched her back disappear at the end of the corridor.In the schoolbag, the bag of her favorite gummies has not been given away yet.',
  '故事性強的文章、有懸念的記敘。': 'A story-telling article and a suspenseful narrative.',
  '整棟樓都聽得到': 'The whole building can hear it',
  '文章主體：': 'Article body:',
  '方向一：': 'Direction one:',
  '方向三（加分）：': 'Direction three (extra points):',
  '方向二：': 'Direction two:',
  '早上起床 → 穿上運動服 → 到達操場 → 比賽開始 → 衝線 → 頒獎': 'Get up in the morning → put on sportswear → arrive at the playground → start the game → cross the line → award the prize',
  '昇華式': 'sublimation',
  '昨日（星期六）下午三時，一名小六學生陳小明在放學回家途中，途經公園時聽到微弱的貓叫聲。他循聲尋找，發現一隻小貓被困在排水渠中。小明沒有猶豫，立即打電話給消防處求助。消防員到場後，用了三十分鐘將小貓安全救出。貓主李太對小明感激不盡，送上感謝卡致意。': 'At 3pm yesterday (Saturday), Chen Xiaoming, a Primary 6 student, was on his way home from school when he heard a faint meowing sound while passing by the park.He followed the sound and found a kitten trapped in a drainage channel.Xiao Ming did not hesitate and immediately called the fire department for help.After firefighters arrived at the scene, it took them thirty minutes to rescue the kitten safely.The cat owner, Mrs. Li, was extremely grateful to Xiao Ming and sent a thank-you card to express her gratitude.',
  '時間 — 昨日（星期六）下午三時 | 地點 — 公園 | 人物 — 陳小明、消防員、貓主李太 | 起因 — 聽到貓叫聲，發現小貓被困排水渠 | 經過 — 致電消防處求助，消防員用三十分鐘救出小貓 | 結果 — 小貓安全獲救，貓主致謝': 'Time - 3 pm yesterday (Saturday) | Location - Park | Characters - Chen Xiaoming, firefighter, cat owner Mrs. Li | Cause - heard the cat meowing and found the kitten trapped in the drainage ditch | Pass - called the fire department for help, the firefighters rescued the kitten in 30 minutes | Result - the kitten was rescued safely, the cat owner expressed thanks',
  '普通版': 'Regular version',
  '暗示方向': 'hint direction',
  '最安全，不易出錯，評卷員容易理解': 'The safest, less error-prone, and easy for reviewers to understand',
  '最少用兩種感官': 'Use at least two senses',
  '最後印象': 'final impression',
  '最終怎樣？': 'What happened in the end?',
  '有一天放學的時候，下起了大雨，我沒有帶雨傘，只好在學校門口等雨停。': 'One day after school, it started to rain heavily. I didn\'t bring an umbrella, so I had to wait for the rain to stop at the school gate.',
  '有五感描寫？有心理層次？有動作分解？': 'Any description of the five senses?Is there a psychological level?Is there an action breakdown?',
  '有修辭手法？句式有變化？': 'Is there a rhetorical device?Has the sentence structure changed?',
  '有具體描寫？（五感：視/聽/嗅/味/觸？）': 'Is there a specific description?(Five senses: sight/hearing/smell/taste/touch?)',
  '有哪些人？': 'Who are there?',
  '有問題': 'There is a problem',
  '有心理描寫？（不只表層感受，有內心獨白和情感變化？）': 'Is there a psychological description?(Not just superficial feelings, but also inner monologues and emotional changes?)',
  '有所回味': 'Have some aftertaste',
  '有畫面感，讀者彷彿身臨其境。': 'It has a sense of picture, and readers feel as if they are immersed in the scene.',
  '根據你想達到的效果來決定': 'Decide based on the effect you want to achieve',
  '極具吸引力，讀者會急著想知道答案。': 'It\'s so engaging that readers will be eager to know the answers.',
  '樸素的力量：': 'The power of simplicity:',
  '檢查重點': 'Check the key points',
  '檢查項目': 'Check items',
  '正確順序：': 'Correct order:',
  '每一篇記敘文，都必須包含以下六個要素，缺一不可：': 'Every narrative must contain the following six elements, all of which are indispensable:',
  '比喻（明喻）': 'Metaphor (simile)',
  '比喻（暗喻）': 'metaphor (metaphor)',
  '比賽記敘、難忘的經歷、想強調結果的文章。': 'Competition narratives, unforgettable experiences, articles that want to highlight results.',
  '比賽記敘、驚險經歷、深刻的體悟。': 'Competition narratives, thrilling experiences, and profound realizations.',
  '比賽過程、跌倒、堅持跑完全程': 'Race process, falls, persistence to finish the race',
  '比賽／精彩事件': 'Competition/Highlights',
  '沒有華麗的修辭，但因為細節夠具體，情感反而更加動人。': 'There are no gorgeous rhetoric, but because the details are specific enough, the emotions are more moving.',
  '清晰直接，讀者馬上知道你要寫什麼。': 'Be clear and direct and readers will immediately know what you are going to write about.',
  '溫度、軟硬、粗糙／光滑': 'Temperature, hardness, roughness/smoothness',
  '溫暖得像火焰': 'warm as fire',
  '滴答、滴答。牆上的時鐘每走一秒，我的手心就多冒一滴汗。桌上攤開的數學課本已經被我翻了無數遍，但那些公式像頑固的敵人，始終不肯乖乖進入我的腦袋。距離數學測驗，還有最後十分鐘。': 'Tick ​​tock, tick tock.Every second the clock on the wall ticks, my palms sweat.I have read through the mathematics textbooks spread out on the table countless times, but those formulas are like stubborn enemies, refusing to enter my head obediently.There are still ten minutes left before the math test.',
  '炯炯有神、目光如炬、眼眶濕潤、眼神黯淡': 'Bright, bright eyes, moist eyes, dim eyes',
  '為什麼發生？': 'Why does it happen?',
  '熱淚盈眶、百感交集、觸景生情、心頭一暖': 'Eyes filled with tears, mixed feelings, touching the scene, feeling warm in my heart',
  '燦爛奪目、燈火輝煌、漆黑一片、昏暗朦朧': 'Brilliant, brilliant, dark, dim',
  '版本：': 'Version:',
  '獨立，': 'independent,',
  '珍惜。」': 'cherish."',
  '生動有力，能立即展現人物關係和衝突。': 'Vivid and powerful, it can immediately show character relationships and conflicts.',
  '生動，讀者能「聽到」語氣': 'Vivid, readers can "hear" the tone',
  '用「像、好像、彷彿、如同」連接兩件事物': 'Use "like, as if, as if, like" to connect two things',
  '用一個畫面、一個動作或一個省略號收尾，讓讀者自己去想像。': 'End with an image, an action, or an ellipsis and let the reader imagine.',
  '用三個或以上結構相似的句子並列': 'Arrange three or more sentences with similar structure',
  '用問題、神秘陳述或驚人事件開頭，讓讀者好奇。': 'Start with a question, mysterious statement, or surprising event to make the reader curious.',
  '用問題製造懸念，畫面感強。讀者會好奇接下來發生了什麼。': 'Use questions to create suspense and have a strong visual sense.The reader will wonder what happened next.',
  '用場景和細節營造緊張氣氛，讀者能「看到」和「感受到」環境。非常有畫面感。': 'Use scenes and details to create tension, and readers can "see" and "feel" the environment.Very graphic.',
  '用相反的事物來強化主體的特徵。': 'Use opposites to reinforce the subject\'s characteristics.',
  '用自己的話寫：「小學六年的時光，轉眼就過去了。」': 'In my own words: "The six years of primary school passed in the blink of an eye."',
  '用詞精準：': 'Precise wording:',
  '用長句鋪墊，用短句收束，製造節奏感。': 'Use long sentences to set the stage and short sentences to conclude to create a sense of rhythm.',
  '留白式': 'blank style',
  '留白想像式': 'blank imagination',
  '的描寫：': 'Description:',
  '的開頭策略，各寫一個開頭段落。（每段 50-80 字）': 'For opening strategies, write an opening paragraph each.(50-80 words per paragraph)',
  '直接交代事件和感受，乾淨俐落。適合考試寫作。': 'Describe events and feelings directly and neatly.Suitable for exam writing.',
  '直接引語': 'direct quotation',
  '直接引語 vs 間接引語：': 'Direct speech vs indirect speech:',
  '直接說 A「是」B，不用「像」': 'Just say A "is" B without "like"',
  '直接說出情緒，但只有一句，不夠深入': 'Express your emotions directly, but only one sentence, not deep enough',
  '看見雨絲斜斜地落下，打在窗戶上畫出彎彎曲曲的水痕（👁️視）；聽見屋簷的雨滴答作響，像一首沒有節拍的樂曲（👂聽）；空氣中聞到泥土被雨水打濕後那股清新的氣味（👃嗅）；伸出手，冰涼的雨點落在掌心（✋觸）。': 'See the raindrops falling slantingly, drawing winding water marks on the windows (👁️sight); hear the raindrops on the eaves, like a piece of music without a beat (👂listen); smell the fresh smell of soil wetted by rain in the air (👃sniff); stretch out your hand, and cold raindrops fall on your palms (✋touch).',
  '知識點': 'Knowledge points',
  '短句：製造張力': 'Short sentence: create tension',
  '禮堂的燈光刺眼得讓人睜不開眼。台下七百多雙眼睛，像七百多顆星星一樣注視著台上的我。我的手緊緊握著講稿，紙張的邊緣已經被我捏得起了皺。': 'The lights in the auditorium were so dazzling that it was hard to keep your eyes open.There were more than 700 pairs of eyes in the audience, staring at me on the stage like more than 700 stars.I held the lecture notes tightly in my hands, and the edges of the paper were wrinkled by my pinching.',
  '穿插往事，讓人物形象更立體': 'Intersperse past events to make the characters more three-dimensional',
  '立意提升與綜合實戰': 'Improvement of intentions and comprehensive implementation',
  '立意清晰？（事件 → 衝突/轉折 → 感悟/成長？）': 'Clear intention?(Event → Conflict/Turning → Enlightenment/Growth?)',
  '站在起跑線前，等待四乘一百米接力賽的開始。': 'Standing in front of the starting line, waiting for the start of the four-by-one-hundred-meter relay race.',
  '笑逐顏開、嫣然一笑、苦笑、勉強擠出笑容': 'Smiling broadly, smiling brightly, smiling bitterly, forcing out a smile',
  '第 1 句（改寫）：': 'Sentence 1 (rewritten):',
  '第 5 句（改寫）：': 'Sentence 5 (rewritten):',
  '第 __ 句潤色：': 'Sentence __ is polished:',
  '第一印象': 'first impression',
  '第一句就直接交代文章的主題或事件。': 'The first sentence directly states the topic or event of the article.',
  '第一層：表層感受': 'The first layer: surface feeling',
  '第一步：事件': 'Step One: Event',
  '第三層：情感變化': 'The third level: emotional changes',
  '第三步：感悟/成長': 'Step 3: Enlightenment/Growth',
  '第二天回到學校，我發現抽屜裡多了一張便利貼。上面是她歪歪斜斜的字跡：「對不起，其實⋯⋯是我先做錯了。」——原來，她比我更早鼓起勇氣。': 'When I returned to school the next day, I found an extra sticky note in my drawer.On it was her crooked handwriting: "I\'m sorry, actually... I made a mistake first." - It turned out that she mustered up the courage earlier than me.',
  '第二層：內心獨白': 'Second level: inner monologue',
  '第二步：衝突/轉折': 'Step Two: Conflict/Turning',
  '答案：': 'Answer:',
  '範文賞析': 'Appreciation of model essays',
  '範文：《運動會的一天》': 'Sample essay: "A Day at the Sports Meet"',
  '精選結尾點評': 'Selected closing comments',
  '終於，我站了起來：「婆婆，您坐這裡吧！」': 'Finally, I stood up: "Mother-in-law, please sit here!"',
  '結尾 A：《第一次參加歌唱比賽》': 'Ending A: "First time participating in a singing competition"',
  '結尾 B：《搬家》': 'Ending B: "Moving"',
  '結尾 C：《一次失敗的考試》': 'Ending C: "A Failed Exam"',
  '結尾 D：《快樂的一天》': 'Ending D: "Happy Day"',
  '結尾出現一個讀者意想不到的轉折，讓人驚訝之後又覺得合情合理。': 'At the end, there is an unexpected twist for readers, which makes people surprised and then feels it makes sense.',
  '結尾回到開頭的畫面、場景或問題，給讀者「圓滿」的感覺。': 'The ending returns to the picture, scene or question at the beginning, giving the reader a sense of "completeness".',
  '結尾是讀者對你的文章留下的': 'The ending is what readers leave behind your article.',
  '結尾有力？不草率？': 'A powerful ending?Not hasty?',
  '結尾有力？（呼應/昇華/留白/反轉？沒犯四大忌？）': 'A powerful ending?(Echo/sublimation/blank/reverse? Didn’t you commit the four taboos?)',
  '經過：': 'go through:',
  '練習一：修辭手法辨識': 'Exercise 1: Identification of rhetorical devices',
  '練習一：動作分解 — 擴寫練習': 'Exercise 1: Action Breakdown - Expansion Exercise',
  '練習一：找出六要素（填空）': 'Exercise 1: Find the six elements (fill in the blanks)',
  '練習一：結尾診斷（判斷好壞）': 'Exercise 1: Ending diagnosis (judging good or bad)',
  '練習一：腦力激盪 — 選材角度練習': 'Exercise 1: Brainstorming - Practice on material selection angles',
  '練習一：開頭類型配對': 'Exercise 1: Pairing of opening types',
  '練習三：對話改造 — 間接引語變直接對話': 'Exercise 3: Conversation Transformation – Change Indirect Speech into Direct Conversation',
  '練習三：為指定題目試寫兩種開頭': 'Exercise 3: Try to write two openings for a given topic',
  '練習三：為文章寫結尾': 'Exercise 3: Write an ending to the article',
  '練習三：自我檢查 — 寫作自評檢核表': 'Exercise Three: Self-Assessment – ​​Writing a Self-Assessment Checklist',
  '練習三：語句潤色 — 「學生腔」改造': 'Exercise 3: Sentence Polishing - Transformation of "Student Tone"',
  '練習三：順敘改倒敘（改寫挑戰）': 'Exercise 3: Change chronological narrative into flashback (rewriting challenge)',
  '練習二：五感填空 — 給場景補入感官描寫': 'Exercise 2: Fill in the blanks with the five senses - add sensory descriptions to the scene',
  '練習二：名家仿寫': 'Exercise 2: Imitation by famous artists',
  '練習二：完整命題寫作（3 選 1）': 'Exercise 2: Complete proposition writing (choose 1 from 3)',
  '練習二：改寫平凡開頭': 'Exercise 2: Rewrite an ordinary beginning',
  '練習二：為文章配對最佳結尾': 'Exercise 2: Pair the best ending for your article',
  '練習二：重組順序（排序）': 'Exercise 2: Reorganize the order (sort)',
  '考試作文、學校生活記敘、大部分日常寫作。': 'Examination compositions, school life narratives, and most daily writing.',
  '考試作文、學校生活記敘。是最穩妥的寫法。': 'Examination compositions and school life narratives.This is the safest way to write.',
  '考試時，旁邊的同學偷偷問我答案。我拒絕了。那天下課後，我們在廁所碰到，氣氛尷尬極了。我忽然明白——做一個「好人」的代價，有時候是孤獨。': 'During the exam, the classmate next to me secretly asked me the answer.I refused.After class that day, we met in the toilet, and the atmosphere was extremely awkward.I suddenly understood - the price of being a "good person" is sometimes loneliness.',
  '考試／測驗': 'Exam/Quiz',
  '聲音的大小、高低、節奏': 'The size, pitch and rhythm of the sound',
  '聽覺描寫：': 'Auditory description:',
  '自由選擇': 'free choice',
  '至少一個比喻': 'at least a metaphor',
  '至少三種感官': 'at least three senses',
  '至少寫出 2 個不同的選材方向：': 'Write down at least 2 different material selection directions:',
  '色彩描寫：': 'Color description:',
  '苦澀的琴聲': 'bitter piano sound',
  '萬里無雲、艷陽高照、碧空如洗、風和日麗': 'There are no clouds in the sky, the sun is shining, the sky is clear, and the wind is gentle.',
  '著我的臉，像母親溫柔的手。」': 'Touching my face, like a mother\'s gentle hands."',
  '表層感受 → 內心獨白 → 情感變化': 'Surface feelings → inner monologue → emotional changes',
  '要做什麼': 'what to do',
  '要有感悟或畫面': 'Need to have feelings or pictures',
  '視覺 · 聽覺 · 嗅覺 · 味覺 · 觸覺': 'Vision · Hearing · Smell · Taste · Touch',
  '解說：按時間順序 — 先交代日期和目的地(B)，然後到達後的動作(D)，接著寫活動過程(C)，最後是結束離開(A)。': 'Explanation: In chronological order - first describe the date and destination (B), then the actions after arrival (D), then the activity process (C), and finally the final departure (A).',
  '記敘文增潤寫作教材': 'Narrative enrichment writing textbook',
  '試試場景式或懸念式': 'Try episodic or suspense style',
  '語言生動？（有用比喻/擬人/排比/誇張？句式有變化？）': 'Vivid language?(Use metaphor/personification/parallel/exaggeration? Is there any change in sentence structure?)',
  '請你用': 'Please use',
  '請判斷以下每個開頭屬於哪種類型：': 'Please determine which type each of the following beginnings belongs to:',
  '請選擇': 'Please select',
  '請選擇⋯⋯': 'Please select⋯⋯',
  '豐滿版（~350字）': 'Full version (~350 words)',
  '輕輕地撫摸': 'caress gently',
  '這件事如何改變了你？你學到了什麼？': 'How did this change you?What did you learn?',
  '這是我們小學階段最後一次運動會': 'This is the last sports meeting in our elementary school',
  '這時，車門打開，一位滿頭白髮的婆婆拄著拐杖，顫巍巍地踏上車。她的背微微佝僂，每走一步都顯得很吃力（👁️視）。車上沒有人動。': 'At this time, the car door opened, and a white-haired mother-in-law stepped onto the car tremblingly on crutches.Her back was slightly stooped, and every step she took seemed laborious (👁️sight).No one moved in the car.',
  '這次考試的分數很低，我感到非常失望。我決定以後要更加用功，爭取下次考到更好的成績。只要努力，一定能成功！': 'I was very disappointed with the low score on this exam.I decided to study harder in the future and strive to get better results next time.As long as you work hard, you will definitely succeed!',
  '通感（感官互通）': 'Synaesthesia (sensory communication)',
  '進階技巧：通感與對比襯托': 'Advanced skills: synesthesia and contrast',
  '過程中': 'in process',
  '適用場合：': 'Applicable occasions:',
  '適用：': 'Applicable:',
  '選擇以下一個題目，運用我們學過的所有技巧，寫一篇完整的記敘文：': 'Choose one of the following topics and write a complete narrative using all the techniques we learned:',
  '選材獨特？有感悟/成長？': 'Unique material selection?Have insights/growth?',
  '選材的視角 — 角度決定高度': 'Perspective of material selection - Angle determines height',
  '避免「有一天⋯⋯」': 'Avoid "One day..."',
  '那一刻，腿上的疲累忽然消失了。取而代之的，是一股溫暖、踏實的感覺在心底升起。（❤️情感變化：從猶豫 → 溫暖踏實）': 'At that moment, the fatigue in my legs suddenly disappeared.Instead, a warm and solid feeling rose in my heart.(❤️Emotional changes: from hesitation → warm and practical)',
  '那一天我沒有撿到銀包，也沒有幫老婆婆過馬路。但我做了一件更難的「小事」——在好朋友面前，堅持了自己相信是對的選擇。而這件事讓我第一次明白，有時候，做對的事情的代價，就是孤獨——但這份孤獨，是值得的。': 'I didn\'t pick up the wallet that day, nor did I help the old lady cross the road.But I did a more difficult "little thing" - in front of my good friends, I insisted on the choice I believed was right.And this incident made me understand for the first time that sometimes, the price of doing the right thing is loneliness - but this loneliness is worth it.',
  '那件事中，有什麼矛盾或困難？': 'What were the contradictions or difficulties in that matter?',
  '那天放學，我一個人走在回家的路上。我一直問自己——我做對了嗎？如果再做一次，我會改變選擇嗎？': '那天放学，我一个人走在回家的路上。 I keep asking myself – am I doing the right thing?If I did it again, would I change my choice?',
  '那是我第一次參加義工活動——到社區的老人院探訪長者。出發前，我以為這只是一次普通的課外活動。': 'That was my first volunteer activity - visiting the elderly in a nursing home in the community.Before setting off, I thought it was just an ordinary extracurricular activity.',
  '那次吵架之後，我才真正明白——友誼不是在風平浪靜時的笑容，而是在風浪過後，依然願意握住彼此的手。一句「對不起」，不是軟弱，而是一種勇氣。': 'After that quarrel, I truly understood that friendship is not about smiles when the storm is calm, but about still being willing to hold each other\'s hands after the storm has passed.Saying "I\'m sorry" is not a sign of weakness, but a sign of courage.',
  '酸甜苦辣鹹、食物的口感': 'Sweet, sour, spicy, salty, the taste of food',
  '重複用詞': 'Repeated words',
  '長短句交替': 'Alternate long and short sentences',
  '開門見山式': 'Straight to the point',
  '開頭一（開門見山式）：': 'Beginning one (straight to the point):',
  '開頭二（場景式 或 懸念式）：': 'Beginning 2 (scenario or suspense):',
  '開頭句子': 'opening sentence',
  '開頭吸引人？（用了開門見山/懸念/場景/對話？）': 'Attractive opening?(Used straight to the point/suspense/scene/dialogue?)',
  '開頭夠吸引人嗎？': 'Is the beginning attractive enough?',
  '開頭寫「陽光穿過窗簾的縫隙⋯⋯」→ 結尾寫「窗簾的縫隙中，那一道金色的光線漸漸暗了下去，但我的心裡，卻有一道光永遠亮著。」': 'Start with "The sun shines through the gap in the curtains..." → End with "In the gaps in the curtains, the golden light gradually dims, but in my heart, there is a light that is always bright."',
  '開頭是讀者對你這篇文章的': 'The beginning is the reader’s response to your article',
  '開頭：': 'beginning:',
  '間接引語': 'indirect speech',
  '閱讀以下句子，辨識它們用了什麼修辭手法：': 'Read the following sentences and identify the rhetorical devices they use:',
  '閱讀以下新聞報導，在空格中填寫對應的六要素：': 'Read the following news reports and fill in the corresponding six elements in the blanks:',
  '陳詞濫調': 'cliche',
  '雖然沒有得獎，但贏得全場掌聲': 'Although he didn’t win an award, he won applause from the audience',
  '需要解釋人物動機、補充背景資訊時。': 'When it is necessary to explain character motivations and supplement background information.',
  '順敘最安全': 'Shunxu is the safest',
  '題目 A：《那一刻，我長大了》': 'Topic A: "At that moment, I grew up"',
  '題目 B：《一份特別的禮物》': 'Topic B: "A Special Gift"',
  '題目 C：《如果時光可以倒流》': 'Topic C: "If Time Could Go Back"',
  '題目：': 'topic:',
  '題目：《難忘的一天》': 'Title: "An Unforgettable Day"',
  '顏色、形狀、大小、光影': 'Color, shape, size, light and shadow',
  '香味、臭味、清新的、刺鼻的': 'Fragrance, stink, fresh, pungent',
  '驚心動魄、扣人心弦、千鈞一髮': 'Thrilling, gripping, critical',
  '骨架：小息鐘聲響了，同學們跑到小食部排隊。小食部很熱鬧，大家都在買自己喜歡的食物。我也在排隊，等著買我的零食。': 'Skeleton: The recess bell rang, and the students ran to the snack bar and lined up.The snack bar is very busy, everyone is buying their favorite food.I was also in line, waiting to buy my snacks.',
  '鴉雀無聲、人聲鼎沸、寂靜無聲、熱火朝天': 'Silence, bustle of people, silence, excitement',
  '點擊左側範文中有顏色的句子，會自動標出對應的要素。': 'Click on the colored sentences in the sample text on the left, and the corresponding elements will be automatically marked.',
  '，每個人都想為班級爭光。': ', everyone wants to win glory for the class.',
  '，讓文章變得生動：': ', make the article come alive:',
  '，陽光還帶著一絲涼意。': ', the sun still has a hint of coolness.',
  '：交代時間、地點、背景（運動會）': ': Explain the time, place and background (sports meeting)',
  '：接力賽開始，順利交棒': ': The relay race begins and the baton is handed over smoothly.',
  '：跌倒後的掙扎與爬起': ': Struggle and get up after falling',
  '：雖然落敗，但獲得比名次更重要的東西': ': Although I lost, I gained something more important than my ranking.',
  '🎬 開頭': '🎬 Beginning',
  '🏁 結尾': '🏁 Ending',
  '👁️ 視覺': '👁️ Vision',
  '👁️ 視覺（看到什麼）：': '👁️ Vision (what you see):',
  '👁️ 視覺：隊伍像一條彎彎曲曲的長龍，從窗口一直延伸到走廊。同學們踮起腳尖，伸長脖子往前張望。': '👁️Visual view: The queue is like a long and winding dragon, extending from the window to the corridor.The students stood on tiptoes, stretched their necks and looked forward.',
  '👂 聽覺': '👂 Hearing',
  '👂 聽覺（聽到什麼）：': '👂 Hearing (what you hear):',
  '👂 聽覺：整個小食部像一個沸騰的市集——此起彼落的叫喊聲、硬幣掉進錢箱的叮噹聲、撕開包裝袋的沙沙聲，混成一片。': '👂 Hearing: The entire snack bar is like a boiling market - the sounds of shouts, the jingle of coins falling into the cash box, and the rustle of tearing open packaging bags, all mixed together.',
  '👃 嗅覺': '👃 Sense of smell',
  '👃 嗅覺（聞到什麼）：': '👃 Smell (what you smell):',
  '👃 嗅覺：空氣中飄著咖哩魚蛋的辛辣味、熱騰騰燒賣的香氣，還有蘋果批的甜絲絲的氣味，讓人忍不住吞了吞口水。': '👃 Smell: The air is filled with the spicy smell of curry fish eggs, the aroma of hot siomai, and the sweet smell of apple slices, which makes people swallow their saliva.',
  '👅 味覺': '👅 Taste',
  '💡 寫作心法：': '💡 Thoughts on writing:',
  '💡 提示：想想一個人生氣時，身體會有什麼動作？臉部表情？手的動作？步伐的速度？': '💡 Tip: Think about what the body does when a person is angry?Facial expression?Hand movements?The speed of the pace?',
  '💡 最佳實踐：長短交錯。': '💡 Best practice: stagger long and short.',
  '💡 立意': '💡 intention',
  '💡 範例 — 寫「雨」：': '💡Example - write "rain":',
  '💡 記敘文的靈魂：': '💡The soul of narrative:',
  '💡 選材心法：': '💡 Thoughts on material selection:',
  '💡 關鍵原則：': '💡 Key principles:',
  '📐 結構': '📐 Structure',
  '📖 好詞好句庫': '📖 A library of good words and sentences',
  '📝 呼應開頭式：回到合照的畫面，形成閉環。': '📝 Echoing the opening statement: return to the picture of the group photo, forming a closed loop.',
  '📝 寫作錦囊': '📝 Writing tips',
  '📝 意外反轉式：讀者以為主角要主動道歉，結果對方先道歉了。': '📝 Unexpected reversal: The reader thought that the protagonist was going to apologize, but the other party apologized first.',
  '📝 感悟昇華式：從具體事件提煉出對友誼的理解。': '📝 Enlightenment sublimation: Extract the understanding of friendship from specific events.',
  '📝 留白想像式：用細節和動作收尾，讀者自己去感受那份未說出口的情感。': '📝 Blank imagination: end with details and actions, and let the readers feel the unspoken emotions by themselves.',
  '📝 結構拆解': '📝 Structural disassembly',
  '📝 記敘文增潤寫作教材': '📝 Narrative enrichment writing textbook',
  '🔍 六要素標註說明': '🔍 Six elements labeling instructions',
  '🔍 賞析筆記': '🔍 Appreciation Notes',
  '🖊️ 描寫': '🖊️ Description',
  '「風': '"wind',
  '人物': 'figure',
  '例子': 'example',
  '修辭': 'rhetoric',
  '倒敘': 'flashback',
  '光影': 'light and shadow',
  '分析': 'analyze',
  '判斷': 'judge',
  '動作': 'action',
  '原因': 'reason',
  '句子': 'sentence',
  '地點': 'Place',
  '場景': 'scene',
  '完成': 'Finish',
  '寫事': 'write things',
  '寫人': 'write about people',
  '寫情': 'write love',
  '寫景': 'describe the scenery',
  '寫法': 'Writing method',
  '寫累': 'Tired of writing',
  '層次': 'level',
  '層面': 'level',
  '快樂': 'hapiness',
  '悲傷': 'sad',
  '意思': 'mean',
  '感動': 'move',
  '排比': 'parallelism',
  '插敘': 'narration',
  '擬人': 'personification',
  '效果': 'Effect',
  '時間': 'time',
  '晴天': 'sunny',
  '暗喻': 'metaphor',
  '橙色': 'orange color',
  '步驟': 'step',
  '氣氛': 'atmosphere',
  '理由': 'reason',
  '發展': 'develop',
  '目錄': 'Table of contents',
  '直接': 'direct',
  '眼睛': 'Eye',
  '神態': 'demeanor',
  '禁忌': 'Taboo',
  '笑容': 'smile',
  '紅色': 'red',
  '紫色': 'Purple',
  '結尾': 'ending',
  '結束': 'Finish',
  '結果': 'result',
  '綠色': 'green',
  '緊張': 'nervous',
  '藍色': 'blue',
  '要素': 'elements',
  '詞語': 'words',
  '誇張': 'exaggerate',
  '語病': 'speech disorder',
  '說明': 'illustrate',
  '起因': 'cause',
  '開始': 'start',
  '開頭': 'beginning',
  '間接': 'indirect',
  '順敘': 'Shunxu',
  '類別': 'category',
  '黃色': 'yellow',
  '明喻': 'Simile (explicit)',
  '經過': 'Process',
  '雨天': 'Rainy Day',
  '高潮': 'Climax',
  '是': 'is',
  '像': 'like / as',
  '→ 問題：太常見、太公式化、沒有個人色彩': '→ Problem: Too common, too formulaic, too impersonal',
  '→ 優點：真實、有衝突、有深度、寫出了人性的複雜': '→ Advantages: Reality, conflict, depth, and the complexity of human nature',
  '→ 結構：具體動作（攀、縮）+ 身體狀態描寫（肥胖）+ 整體印象（努力的樣子）': '→ Structure: specific actions (climbing, retracting) + description of body condition (obesity) + overall impression (looking like trying hard)',
  '→ 適合緊張時刻、動作描寫、製造懸念': '→ Suitable for tense moments, action description, and creating suspense',
  '→ 適合抒情、描寫場景、營造平靜的氣氛': '→ Suitable for lyrical expression, scene description, and creating a calm atmosphere',
};
